overseer_db  | The files belonging to this database system will be owned by user "postgres".
overseer_db  | This user must also own the server process.
overseer_db  | 
overseer_db  | The database cluster will be initialized with locale "en_US.utf8".
overseer_db  | The default database encoding has accordingly been set to "UTF8".
overseer_db  | The default text search configuration will be set to "english".
overseer_db  | 
overseer_db  | Data page checksums are disabled.
overseer_db  | 
overseer_db  | fixing permissions on existing directory /var/lib/postgresql/data ... ok
overseer_db  | creating subdirectories ... ok
overseer_db  | selecting dynamic shared memory implementation ... posix
overseer_db  | selecting default max_connections ... 100
overseer_db  | selecting default shared_buffers ... 128MB
overseer_db  | selecting default time zone ... Etc/UTC
overseer_db  | creating configuration files ... ok
overseer_db  | running bootstrap script ... ok
overseer_db  | performing post-bootstrap initialization ... ok
overseer_db  | initdb: warning: enabling "trust" authentication for local connections
overseer_db  | You can change this by editing pg_hba.conf or using the option -A, or
overseer_db  | --auth-local and --auth-host, the next time you run initdb.
overseer_db  | syncing data to disk ... ok
overseer_db  | 
overseer_db  | 
overseer_db  | Success. You can now start the database server using:
overseer_report  | Traceback (most recent call last):
overseer_report  |   File "/usr/local/bin/uvicorn", line 8, in <module>
overseer_report  |     sys.exit(main())
overseer_report  |              ^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
overseer_report  |     return self.main(*args, **kwargs)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1082, in main
overseer_report  |     rv = self.invoke(ctx)
overseer_report  |          ^^^^^^^^^^^^^^^^
overseer_crud    | Traceback (most recent call last):
overseer_crud    |   File "/usr/local/bin/uvicorn", line 8, in <module>
overseer_crud    |     sys.exit(main())
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
overseer_report  |     return ctx.invoke(self.callback, **ctx.params)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 788, in invoke
overseer_report  |     return __callback(*args, **kwargs)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 413, in main
overseer_report  |     run(
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 580, in run
overseer_report  |     server.run()
overseer_crud    |     return self.main(*args, **kwargs)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1082, in main
overseer_crud    |     rv = self.invoke(ctx)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
overseer_crud    |     return ctx.invoke(self.callback, **ctx.params)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 788, in invoke
overseer_crud    |     return __callback(*args, **kwargs)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 413, in main
overseer_crud    |     run(
overseer_db      | 
overseer_db      |     pg_ctl -D /var/lib/postgresql/data -l logfile start
overseer_db      | 
overseer_db      | waiting for server to start....2025-04-15 20:09:34.156 UTC [48] LOG:  starting PostgreSQL 13.20 (Debian 13.20-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
overseer_db      | 2025-04-15 20:09:34.160 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
overseer_db      | 2025-04-15 20:09:34.165 UTC [49] LOG:  database system was shut down at 2025-04-15 20:09:32 UTC
overseer_db      | 2025-04-15 20:09:34.174 UTC [48] LOG:  database system is ready to accept connections
overseer_db      |  done
overseer_db      | server started
overseer_db      | CREATE DATABASE
overseer_db      | 
overseer_db      | 
overseer_db      | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
overseer_db      | 
overseer_db      | 2025-04-15 20:09:35.871 UTC [48] LOG:  received fast shutdown request
overseer_db      | waiting for server to shut down....2025-04-15 20:09:35.884 UTC [48] LOG:  aborting any active transactions
overseer_db      | 2025-04-15 20:09:35.888 UTC [48] LOG:  background worker "logical replication launcher" (PID 55) exited with exit code 1
overseer_db      | 2025-04-15 20:09:35.888 UTC [50] LOG:  shutting down
overseer_db      | 2025-04-15 20:09:36.059 UTC [48] LOG:  database system is shut down
overseer_db      |  done
overseer_db      | server stopped
overseer_db      | 
overseer_db      | PostgreSQL init process complete; ready for start up.
overseer_db      | 
overseer_db      | 2025-04-15 20:09:36.137 UTC [1] LOG:  starting PostgreSQL 13.20 (Debian 13.20-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
overseer_db      | 2025-04-15 20:09:36.137 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
overseer_db      | 2025-04-15 20:09:36.137 UTC [1] LOG:  listening on IPv6 address "::", port 5432
overseer_db      | 2025-04-15 20:09:36.169 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
overseer_db      | 2025-04-15 20:09:36.207 UTC [63] LOG:  database system was shut down at 2025-04-15 20:09:36 UTC
overseer_db      | 2025-04-15 20:09:36.233 UTC [1] LOG:  database system is ready to accept connections
overseer_db      | 2025-04-15 20:09:53.969 UTC [1] LOG:  received fast shutdown request
overseer_db      | 2025-04-15 20:09:53.970 UTC [1] LOG:  aborting any active transactions
overseer_db      | 2025-04-15 20:09:53.975 UTC [1] LOG:  background worker "logical replication launcher" (PID 69) exited with exit code 1
overseer_db      | 2025-04-15 20:09:53.976 UTC [64] LOG:  shutting down
overseer_db      | 2025-04-15 20:09:53.993 UTC [1] LOG:  database system is shut down
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 66, in run
overseer_report  |     return asyncio.run(self.serve(sockets=sockets))
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
overseer_report  |     return runner.run(main)
overseer_report  |            ^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
overseer_report  |     return self._loop.run_until_complete(task)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 70, in serve
overseer_report  |     await self._serve(sockets)
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 77, in _serve
overseer_report  |     config.load()
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 435, in load
overseer_report  |     self.loaded_app = import_from_string(self.app)
overseer_report  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 22, in import_from_string
overseer_report  |     raise exc from None
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
overseer_report  |     module = importlib.import_module(module_str)
overseer_report  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
overseer_report  |     return _bootstrap._gcd_import(name[level:], package, level)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
overseer_report  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
overseer_report  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
overseer_report  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
overseer_report  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
overseer_report  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
overseer_report  |   File "/reports/main.py", line 3, in <module>
overseer_report  |     from models import Item
overseer_report  | ModuleNotFoundError: No module named 'models'
overseer_report  | Traceback (most recent call last):
overseer_report  |   File "/usr/local/bin/uvicorn", line 8, in <module>
overseer_report  |     sys.exit(main())
overseer_report  |              ^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1161, in __call__
overseer_report  |     return self.main(*args, **kwargs)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1082, in main
overseer_report  |     rv = self.invoke(ctx)
overseer_report  |          ^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1443, in invoke
overseer_report  |     return ctx.invoke(self.callback, **ctx.params)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 788, in invoke
overseer_report  |     return __callback(*args, **kwargs)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 413, in main
overseer_report  |     run(
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 580, in run
overseer_report  |     server.run()
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 66, in run
overseer_report  |     return asyncio.run(self.serve(sockets=sockets))
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
overseer_report  |     return runner.run(main)
overseer_report  |            ^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
overseer_report  |     return self._loop.run_until_complete(task)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 70, in serve
overseer_report  |     await self._serve(sockets)
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 77, in _serve
overseer_report  |     config.load()
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 435, in load
overseer_report  |     self.loaded_app = import_from_string(self.app)
overseer_report  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 22, in import_from_string
overseer_report  |     raise exc from None
overseer_report  |   File "/usr/local/lib/python3.11/site-packages/uvicorn/importer.py", line 19, in import_from_string
overseer_report  |     module = importlib.import_module(module_str)
overseer_report  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
overseer_report  |     return _bootstrap._gcd_import(name[level:], package, level)
overseer_report  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
overseer_report  |   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
overseer_report  |   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
overseer_report  |   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
overseer_report  |   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
overseer_report  |   File "<frozen importlib._bootstrap_external>", line 940, in exec_module
overseer_report  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
overseer_report  |   File "/reports/main.py", line 3, in <module>
overseer_report  |     from models import Item
overseer_report  | ModuleNotFoundError: No module named 'models'
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 580, in run
overseer_crud    |     server.run()
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 66, in run
overseer_crud    |     return asyncio.run(self.serve(sockets=sockets))
overseer_crud    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
overseer_crud    |     return loop.run_until_complete(main)
overseer_crud    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
overseer_crud    |     return future.result()
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 70, in serve
overseer_crud    |     await self._serve(sockets)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 77, in _serve
overseer_crud    |     config.load()
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 435, in load
overseer_crud    |     self.loaded_app = import_from_string(self.app)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
overseer_crud    |     module = importlib.import_module(module_str)
overseer_crud    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
overseer_crud    |     return _bootstrap._gcd_import(name[level:], package, level)
overseer_crud    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
overseer_crud    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
overseer_crud    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
overseer_crud    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
overseer_crud    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
overseer_crud    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
overseer_crud    |   File "/app/main.py", line 4, in <module>
overseer_crud    |     from models import Item
overseer_crud    |   File "/app/models.py", line 4, in <module>
overseer_crud    |     from .database import Base
overseer_crud    | ImportError: attempted relative import with no known parent package
overseer_crud    | Traceback (most recent call last):
overseer_crud    |   File "/usr/local/bin/uvicorn", line 8, in <module>
overseer_crud    |     sys.exit(main())
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1161, in __call__
overseer_crud    |     return self.main(*args, **kwargs)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1082, in main
overseer_crud    |     rv = self.invoke(ctx)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1443, in invoke
overseer_crud    |     return ctx.invoke(self.callback, **ctx.params)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/click/core.py", line 788, in invoke
overseer_crud    |     return __callback(*args, **kwargs)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 413, in main
overseer_crud    |     run(
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/main.py", line 580, in run
overseer_crud    |     server.run()
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 66, in run
overseer_crud    |     return asyncio.run(self.serve(sockets=sockets))
overseer_crud    |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
overseer_crud    |     return loop.run_until_complete(main)
overseer_crud    |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
overseer_crud    |     return future.result()
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 70, in serve
overseer_crud    |     await self._serve(sockets)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/server.py", line 77, in _serve
overseer_crud    |     config.load()
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/config.py", line 435, in load
overseer_crud    |     self.loaded_app = import_from_string(self.app)
overseer_crud    |   File "/usr/local/lib/python3.10/site-packages/uvicorn/importer.py", line 19, in import_from_string
overseer_crud    |     module = importlib.import_module(module_str)
overseer_crud    |   File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
overseer_crud    |     return _bootstrap._gcd_import(name[level:], package, level)
overseer_crud    |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
overseer_crud    |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
overseer_crud    |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
overseer_crud    |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
overseer_crud    |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
overseer_crud    |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
overseer_crud    |   File "/app/main.py", line 4, in <module>
overseer_crud    |     from models import Item
overseer_crud    |   File "/app/models.py", line 4, in <module>
overseer_crud    |     from .database import Base
overseer_crud    | ImportError: attempted relative import with no known parent package
